Bert make PR
PaidPaper/public pull request #2378
Opened 2024-03-10 10:25 UTC by bert-griffin

2024-03-10 10:25 UTC, wanda-carlson commented
This looks cool

2024-03-10 10:27 UTC, bert-griffin commented
How about now ?

2024-03-10 10:27 UTC, wanda-carlson commented
@bert-griffin Is this oaky ?

2024-03-10 10:27 UTC, bert-griffin commented
@wanda-carlson Yes

2024-03-10 10:27 UTC, wanda-carlson requested changes

2024-03-10 10:27 UTC, wanda-carlson commented on src/foo.py
> +    print("Hello foo3")
```suggestion
    print("Bert make change")
```

2024-03-10 10:28 UTC, wanda-carlson commented on src/foo.py
> +    print("Bert make change")
```suggestion
    print("Bert make nice change")
```

2024-03-10 10:29 UTC, bert-griffin commented on src/foo.py
> +    print("Bert make nice change")
```suggestion
    print("Bert make nice change wow")
```

2024-03-10 10:32 UTC, bert-griffin commented on src/foo.py
> +    print("Bert make nice change wow")
```suggestion
    print("Bert make nice change wow")
    print("Bert make nice change wow")
```

2024-03-20 20:16 UTC, wanda-carlson commented
asdfasdf

2024-07-04 06:21 UTC, closed without merging