Update README.md
PaidPaper/public pull request #315
Opened 2022-06-29 14:55 UTC by wanda-carlson

Anna testing core features.

2022-06-29 15:05 UTC, wanda-carlson commented
**Bert Griffin** pls check

2022-06-29 19:00 UTC, bert-griffin requested changes
@wanda-carlson requested changes 111

2022-06-29 19:05 UTC, wanda-carlson reviewed
ok

2022-06-29 19:33 UTC, wanda-carlson commented
hi

2022-06-29 19:35 UTC, wanda-carlson commented
delete

2022-06-29 19:36 UTC, chad-daniels commented
delete

2022-06-30 14:43 UTC, chad-daniels reviewed
![Screenshot (11)](https://user-images.githubusercontent.com/87614205/176706422-c8c98ca8-703d-44d5-84e9-b91f7b716ac5.png)
Changes requested

2022-06-30 14:45 UTC, wanda-carlson reviewed
resolve testing

2022-06-30 16:46 UTC, wanda-carlson commented on README.md
> +
resolve

2022-07-28 07:10 UTC, closed without merging