Update README.md
PaidPaper/public pull request #338
Opened 2022-07-25 17:34 UTC by wanda-carlson

2022-07-25 17:39 UTC, wanda-carlson commented
![Screenshot (12)](https://user-images.githubusercontent.com/87515018/180840109-7e8b858d-64ab-4103-9d37-7b20b383ba29.png)
comment Github

2022-07-25 17:41 UTC, wanda-carlson commented
Comment Slack
[Screenshot (86).png](https://files.slack.com/files-pri/T0289BY1FK4-F03QWT2NQ3U/screenshot__86_.png)

2022-07-25 17:42 UTC, wanda-carlson commented
![Uploading Screenshot (86).png…]()

2022-07-26 06:38 UTC, wanda-carlson commented
**Pullflow** assign @wanda-carlson

2022-07-26 06:52 UTC, wanda-carlson reviewed
Can you check this **Bert Griffin**

2022-07-26 06:52 UTC, wanda-carlson commented
Can you check this @bert-griffin

2022-07-26 06:54 UTC, wanda-carlson reviewed
It looks ok

2022-07-26 06:55 UTC, wanda-carlson reviewed
Thanks, I'll "update" it.

2022-07-26 09:14 UTC, chad-daniels commented
hi

2022-07-26 09:19 UTC, chad-daniels requested changes

2022-07-26 09:19 UTC, chad-daniels commented on README.md
> +Changes
@wanda please change

2022-07-26 09:21 UTC, chad-daniels requested changes
minor changes please

2022-07-26 09:21 UTC, chad-daniels approved these changes

2022-07-26 09:24 UTC, chad-daniels commented
delete

2022-07-26 09:24 UTC, chad-daniels commented
edit edit

2022-07-26 09:25 UTC, chad-daniels commented
delete

2022-07-26 09:25 UTC, chad-daniels commented
edit

2022-07-26 09:36 UTC, chad-daniels reviewed
It looks ok

2022-07-28 07:10 UTC, closed without merging