move channel
PaidPaper/public pull request #73
Opened 2022-01-24 23:21 UTC by wanda-carlson

2022-01-25 03:13 UTC, wanda-carlson commented
comment

2022-01-27 07:54 UTC, wanda-carlson commented
Cool stuff! 
<img width="557" alt="Screen Shot 2022-01-11 at 3 40 53 PM" src="https://user-images.githubusercontent.com/87515018/151315114-31e700dc-5f95-44db-b887-5f13cd10e60b.png">

2022-01-27 07:55 UTC, henry-richard commented
Good stuff

2022-01-27 09:01 UTC, henry-richard commented
Hi wanda

2022-01-27 09:05 UTC, henry-richard commented
Hi wanda

2022-01-27 09:07 UTC, henry-richard commented
Hello Wandy

2022-01-27 09:07 UTC, henry-richard commented
Henry is here now

2022-01-27 09:11 UTC, henry-richard commented
Wanda wandaaa

2022-01-27 09:11 UTC, henry-richard commented
wanda 2

2022-01-28 07:37 UTC, wanda-carlson commented on README.md
> +
this is weird

2022-01-28 07:41 UTC, wanda-carlson commented on README.md
> +
Wanda1

2022-01-28 07:43 UTC, wanda-carlson commented on README.md
> +
Zainab's comment

2022-01-28 07:44 UTC, wanda-carlson commented on README.md
> +
Another Zainab comment

2022-01-30 04:10 UTC, wanda-carlson commented
Hi

2022-01-30 04:10 UTC, wanda-carlson commented
Hello

2022-01-30 04:20 UTC, wanda-carlson commented
Here's a picture
[Screen Shot 2022-01-06 at 7.59.26 AM.png](https://files.slack.com/files-pri/T0289BY1FK4-F0316B8EJGH/screen_shot_2022-01-06_at_7.59.26_am.png)

2022-01-30 04:25 UTC, wanda-carlson commented
<img width="291" alt="Screen Shot 2022-01-10 at 10 25 58 AM" src="https://user-images.githubusercontent.com/87515018/151686579-d6c01b61-b8c3-4104-a4c9-dcfa5e11548f.png">

2022-01-30 05:10 UTC, wanda-carlson commented
Not a picture
[README.md](https://github.com/PaidPaper/public/files/7965333/README.md)

2022-01-30 05:10 UTC, wanda-carlson commented
Not picture
[README.md](https://github.com/PaidPaper/public/files/7965334/README.md)

2022-01-30 05:40 UTC, wanda-carlson commented
image attachment
<img width="565" alt="Screen Shot 2022-01-24 at 9 16 53 AM" src="https://user-images.githubusercontent.com/87515018/151688132-1ef23a4d-d9d7-4ab9-bcee-687d9cc10ca2.png">

2022-01-30 06:21 UTC, wanda-carlson commented
This is an image...
<img width="291" alt="Screen Shot 2022-01-10 at 10 25 58 AM" src="https://user-images.githubusercontent.com/87515018/151689093-31d176cd-dc1b-4105-ab9c-52f2b57d20ee.png">

2022-01-30 06:30 UTC, wanda-carlson commented
Readme file here
[README.md](https://github.com/PaidPaper/public/files/7965418/README.md)

2022-01-30 06:44 UTC, wanda-carlson commented
This is another image
[Screen Shot 2022-01-06 at 7.59.26 AM.png](https://files.slack.com/files-pri/T0289BY1FK4-F0316B8EJGH/screen_shot_2022-01-06_at_7.59.26_am.png)

2022-01-30 07:10 UTC, wanda-carlson commented
This is an image
<img width="565" alt="Screen Shot 2022-01-24 at 9 16 53 AM" src="https://user-images.githubusercontent.com/87515018/151690358-c86bf325-eeb0-4593-8d96-6b25e5412887.png">

2022-02-04 06:34 UTC, henry-richard requested changes
Make some changes

2022-02-04 06:34 UTC, henry-richard approved these changes
Looking good!

2022-02-04 06:35 UTC, henry-richard commented
```Some pictures and information```
<img width="376" alt="Screen Shot 2022-01-27 at 9 57 21 PM" src="https://user-images.githubusercontent.com/87513666/152483416-d1b2b0bf-b5d8-4ed6-a8c6-add989848cf1.png">

2022-02-07 07:29 UTC, henry-richard approved these changes
Nice WOrk!

2022-02-07 07:32 UTC, wanda-carlson commented
Can i merge this? **Henry Richard**

2022-02-07 07:32 UTC, henry-richard commented
Go ahead

2022-02-07 07:33 UTC, closed without merging